name: mafatih
description: Mafatih
version: 1.0.0+2050

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_automation: ^2.0.0
#  admob_flutter: ^3.0.0
  flutter_localizations:
    sdk: flutter

#  cupertino_icons: ^1.0.5
  provider: ^6.0.5
#  pk_skeleton: ^0.0.2
#  json_annotation: ^4.8.0
#  flutter_svg: ^2.0.9
#  shared_preferences: ^2.1.0
  fluttertoast: ^8.0.3
  url_launcher: ^6.1.10
  package_info: ^2.0.2
#  flutter_markdown: ^0.7.1
  dotted_border: ^2.0.0+3
  easy_localization: ^3.0.1
#  dio: ^5.1.1
#  http: ^0.13.5
#  flutter_spinkit: ^5.2.0
  screen_brightness: ^0.2.2
#  flutter_local_notifications: ^17.0.1
#  device_apps: ^2.1.1
  cached_network_image: ^3.2.3
  week_of_year: ^2.0.0
  just_audio: ^0.9.32
#  audio_session: ^0.1.13
#  audio_service: ^0.18.9
#  path_provider: ^2.0.14
  encrypt: ^5.0.1
#  flutter_media_metadata: ^1.0.0+1
#  connectivity_plus: ^6.0.3
#  google_mobile_ads: ^2.0.0
#  screen: ^0.0.5
#  adivery: ^4.2.0
#  tapsell_plus: ^2.1.7
  share_plus: ^9.0.0
#  pin_code_fields: ^8.0.1
#  video_player: ^2.4.8
#  image_picker: ^1.0.1
#  crop: ^0.5.2
#  audioplayers: ^6.0.0
#  better_audio_picker_plugin: ^0.0.6
#  permission_handler: ^11.0.1
  flutter_staggered_grid_view: ^0.7.0
  keep_screen_on: ^3.0.0
#  connectivity: ^3.0.6
  internet_connection_checker: ^1.0.0+1
  media_kit: ^1.1.10                             # Primary package.
  media_kit_video: ^1.2.4                        # For video rendering.
  media_kit_libs_video: ^1.0.4                   # Native video dependencies.
#  package_info_plus: ^8.0.0
  google_mobile_ads: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - python/Babs/
    - python/Babs/infobabs/
    - python/Babs/1/
    - python/Babs/2/
    - python/Babs/3/
    - python/Babs/4/
    - python/Babs/5/
    - python/Babs/6/
    - python/Babs/71/
    - python/Babs/72/
    - python/Babs/73/
    - python/Babs/74/
    - python/Babs/75/
    - python/Babs/76/
    - python/Babs/77/
    - assets/lang/
    - assets/sounds/
    - assets/icons/

  fonts:
    - family: far_nazanin
      fonts:
        - asset: fonts/far_nazanin.ttf

    - family: IRAN SansMobile(NoEn)
      fonts:
        - asset: fonts/IRANSansMobile(NoEn).ttf

    - family: عربی ساده
      fonts:
        - asset: fonts/AdobeArabic_Regular.otf

    - family:  MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf

    - family:  IRANSans
      fonts:
        - asset: fonts/IRANSans.ttf

    - family:  نیریزی دو
      fonts:
        - asset: fonts/arabicNeirizi.ttf

    - family:  me_quran
      fonts:
        - asset: fonts/me_quran.ttf

    - family:  قرآن طاها
      fonts:
        - asset: fonts/QuranTaha.ttf

    - family:  نیریزی یک
      fonts:
        - asset: fonts/Neirizi.ttf

    - family:  زر
      fonts:
        - asset: fonts/ZAR New.ttf

    - family:  القلم
      fonts:
        - asset: fonts/Al Qalam New.ttf

    - family: عثمان طه ۱
      fonts:
        - asset: fonts/KFGQPC Uthman Taha Naskh Regular.ttf

    - family: عثمان طه ۲
      fonts:
        - asset: fonts/ScheherazadeRegOT.ttf