name: mafatih
description: Mafatih
version: 1.0.0+29

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_automation: ^1.1.4
  admob_flutter: ^1.0.1
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^4.0.5
  pk_skeleton: ^0.0.2
  json_annotation: ^3.0.1
  flutter_svg: ^0.19.3
  shared_preferences: ^0.5.7+3
  fluttertoast: ^8.0.3
  url_launcher: ^5.0.0
  package_info: ^0.4.1
  flutter_markdown: ^0.5.1
  dotted_border: ^1.0.5
  easy_localization: ^2.3.3+1
  dio: ^3.0.10
  http: ^0.12.2
  flutter_spinkit: ^4.1.2+1
  flutter_screen: ^0.0.2
  flutter_local_notifications: ^1.5.0+1
  device_apps: ^2.1.1
  cached_network_image: ^2.5.1
  week_of_year: ^2.0.0
  just_audio: ^0.6.15+1
  audio_session: ^0.0.11
  audio_service: ^0.16.2+1
  path_provider: ^1.6.28
  encrypt: ^4.1.0
  flutter_media_metadata: ^1.0.0+1
  connectivity_plus: ^0.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - python/Babs/
    - python/Babs/infobabs/
    - python/Babs/1/
    - python/Babs/2/
    - python/Babs/3/
    - python/Babs/4/
    - python/Babs/5/
    - python/Babs/6/
    - python/Babs/70/
    - python/Babs/71/
    - python/Babs/72/
    - python/Babs/73/
    - python/Babs/74/
    - python/Babs/75/
    - python/Babs/76/
    - python/Babs/77/
    - assets/lang/
    - assets/sounds/

  fonts:
    - family: far_nazanin
      fonts:
        - asset: fonts/far_nazanin.ttf

    - family: IRAN SansMobile(NoEn)
      fonts:
        - asset: fonts/IRANSansMobile(NoEn).ttf

    - family: عربی ساده
      fonts:
        - asset: fonts/AdobeArabic_Regular.otf

    - family:  MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf

    - family:  IRANSans
      fonts:
        - asset: fonts/IRANSans.ttf

    - family:  نیریزی دو
      fonts:
        - asset: fonts/arabicNeirizi.ttf

    - family:  me_quran
      fonts:
        - asset: fonts/me_quran.ttf

    - family:  قرآن طاها
      fonts:
        - asset: fonts/QuranTaha.ttf

    - family:  نیریزی یک
      fonts:
        - asset: fonts/Neirizi.ttf

    - family:  زر
      fonts:
        - asset: fonts/ZAR New.ttf

    - family:  القلم
      fonts:
        - asset: fonts/Al Qalam New.ttf

    - family:  usman
      fonts:
        - asset: fonts/usmanTaha.ttf