name: mafatih
description: Mafatih
version: 1.0.0+13

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_automation: ^1.1.4

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^4.0.5
  pk_skeleton: ^0.0.2
  # package_info: ^0.4.0+17
  #  flutter_compass: ^0.4.1
#  permission_handler: ^5.0.0+hotfix.4
  # http: ^0.12.0+4
  #  geolocator: ^5.3.1
  json_annotation: ^3.0.1
  flutter_svg: ^0.17.4
  #  hexcolor: ^1.0.2
  shared_preferences: ^0.5.7+3
  screen: ^0.0.5
  fluttertoast: ^3.1.3
  #  launch_review: ^1.0.1
  #  intent: ^1.3.4
  #  android_intent: ^0.3.7+2
  #  device_apps:
  url_launcher: ^5.0.0
  # animated_splash: ^1.0.0
  package_info: ^0.4.1
  flutter_markdown: ^0.5.1

  #  firebase_remote_config: ^0.3.1+1
  dio: ^3.0.10
  http: ^0.12.2
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/
    - python/Babs/
    - python/Babs/1/
    - python/Babs/2/
    - python/Babs/3/
    - python/Babs/4/
    - python/Babs/5/

  fonts:
    - family: far_nazanin
      fonts:
        - asset: fonts/far_nazanin.ttf

    - family: IRAN SansMobile(NoEn)
      fonts:
        - asset: fonts/IRANSansMobile(NoEn).ttf

    - family: عربی ساده
      fonts:
        - asset: fonts/AdobeArabic_Regular.otf

    - family:  MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf

    - family:  IRANSans
      fonts:
        - asset: fonts/IRANSans.ttf

    - family:  نیریزی دو
      fonts:
        - asset: fonts/arabicNeirizi.ttf

    - family:  me_quran
      fonts:
        - asset: fonts/me_quran.ttf

    - family:  قرآن طاها
      fonts:
        - asset: fonts/QuranTaha.ttf

    - family:  نیریزی یک
      fonts:
        - asset: fonts/Neirizi.ttf

    - family:  زر
      fonts:
        - asset: fonts/ZAR New.ttf

    - family:  القلم
      fonts:
        - asset: fonts/Al Qalam New.ttf